CREATE TYPE "Role" AS ENUM ('STUDENT','COMPANY','ADMIN');
CREATE TABLE "User" ("id" TEXT NOT NULL,"email" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"role" "Role" NOT NULL,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE TABLE "Student" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"name" TEXT NOT NULL,"resumeUrl" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Student_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Student_userId_key" ON "Student"("userId");
CREATE TABLE "Company" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"name" TEXT NOT NULL,"logoUrl" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Company_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Company_userId_key" ON "Company"("userId");
CREATE TABLE "Internship" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"location" TEXT NOT NULL,"category" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Internship_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Internship_location_idx" ON "Internship"("location"); CREATE INDEX "Internship_category_idx" ON "Internship"("category"); CREATE INDEX "Internship_createdAt_idx" ON "Internship"("createdAt"); CREATE INDEX "Internship_companyId_createdAt_idx" ON "Internship"("companyId","createdAt");
ALTER TABLE "Student" ADD CONSTRAINT "Student_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Company" ADD CONSTRAINT "Company_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Internship" ADD CONSTRAINT "Internship_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE;