import {useEffect,useState} from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:4000/api";
type Row={id:string;title:string;location:string;category:string;createdAt:string;company:{name:string;logoUrl:string|null}};type Page={data:Row[];page:number;limit:number;total:number;totalPages:number};
function App(){const[q,setQ]=useState(""),[search,setSearch]=useState(""),[location,setLocation]=useState(""),[category,setCategory]=useState(""),[sort,setSort]=useState("created_desc"),[page,setPage]=useState(1),[data,setData]=useState<Page|null>(null),[opts,setOpts]=useState({locations:[] as string[],categories:[] as string[]}),[loading,setLoading]=useState(true),[note,setNote]=useState("");
useEffect(()=>{const t=setTimeout(()=>{setSearch(q);setPage(1)},400);return()=>clearTimeout(t)},[q]);
useEffect(()=>{fetch(API+"/internships/options").then(r=>r.json()).then(setOpts)},[]);
useEffect(()=>{setLoading(true);const p=new URLSearchParams({search,location,category,sort,page:String(page),limit:"12"});fetch(API+"/internships?"+p).then(r=>r.json()).then(setData).finally(()=>setLoading(false))},[search,location,category,sort,page]);
async function signIn(){const email=prompt("Email","student@example.com")||"";const password=prompt("Password","DemoPass1!")||"";const r=await fetch(API+"/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(r.ok){localStorage.setItem("token",d.token);setNote("Signed in as "+d.user.role)}else setNote(d.error?.message||"Sign-in failed")}
async function resume(e:any){const f=e.target.files?.[0],token=localStorage.getItem("token");if(!f||!token){setNote("Sign in before uploading.");return}const me=await fetch(API+"/me",{headers:{Authorization:"Bearer "+token}}).then(r=>r.json());const fd=new FormData();fd.append("file",f);const r=await fetch(API+"/students/"+me.student.id+"/resume",{method:"POST",headers:{Authorization:"Bearer "+token},body:fd});const d=await r.json();setNote(r.ok?"Resume uploaded successfully.":d.error?.message||"Upload failed")}
return <main><header><div><small>TalentBridge</small><h1>Internship catalog</h1><p>Server-side search, filters and pagination for real data volume.</p></div><button onClick={signIn}>Demo sign in</button></header><section className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search title or company…" aria-label="Search"/><select value={location} onChange={e=>{setLocation(e.target.value);setPage(1)}}><option value="">All locations</option>{opts.locations.map(x=><option key={x}>{x}</option>)}</select><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="">All categories</option>{opts.categories.map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option value="created_desc">Newest</option><option value="created_asc">Oldest</option><option value="title_asc">Title A–Z</option><option value="title_desc">Title Z–A</option></select><label className="upload">Upload PDF resume<input type="file" accept="application/pdf" onChange={resume}/></label></section>{note&&<div className="note">{note}</div>}{loading?<div className="grid">{[1,2,3,4,5,6].map(x=><div className="card skeleton" key={x}/>)}</div>:data?.data.length?<div className="grid">{data.data.map(x=><article className="card" key={x.id}><small>{x.category}</small><h2>{x.title}</h2><b>{x.company.name}</b><p>{x.location}</p><small>{new Date(x.createdAt).toLocaleDateString()}</small></article>)}</div>:<div className="empty"><h2>No internships found</h2><p>Clear a filter or change your search.</p></div>}{data&&<nav className="pager"><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {Math.max(data.totalPages,1)} · {data.total} results</span><button disabled={page>=data.totalPages} onClick={()=>setPage(page+1)}>Next</button></nav>}</main>}
createRoot(document.getElementById("root")!).render(<App/>);